[phases.install]
cmds = [
    "rm -rf /opt/venv",
    "python -m venv --symlinks /opt/venv",
    ". /opt/venv/bin/activate && pip install -r requirements.txt"
]



[start]
command = "uvicorn src.main:app --host 0.0.0.0 --port 8000"
